# docker-compose.yml
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - bd
    environment:
      BD_HOST: bd
      BD_USER: root
      BD_PASSWORD: password
      BD_DATABASE: buscaliza_bd

  bd:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: buscaliza_bd
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: